### PR TITLE
Port deprecated Qt uses

### PR DESCRIPTION
**Pull request by JBBgameich**
While I was working on this, QList::toSet was deprecated, so this doesn't port all deprecated parts anymore.

### CODE REVIEW

**Comment by JBBgameich** [comment]
Since the ci seems to use Qt 5.9, it would be necessary to test this on Qt 5.6 manually.

**Comment by JBBgameich** [comment]
Managed to build it on Qt 5.7 with the latest commits

**Comment by Kaffeine** [comment]
I'm building the PR with Qt 5.6 [here](https://build.merproject.org/package/show/home:Kaffeine:test/telepathy-qt5).
Let's merge it as soon as it compiles. (already LGTM)
I'll rebase my clang-tidy commits and merge them right after yours.

**Comment by Kaffeine** [comment]
Build complete.

**Pull request merged**
